package com.example.galibaapp_semestralka.navigation

enum class Screens {

    HOME, FOLLOW, LOGIN, REGISTER, PERSONAL_USER_PROFILE, EDIT_USER_PROFILE, USER_PROFILE, CREATE_EVENT, EDIT_EVENT, ROOT, AUTHROOT, HOMEROOT,USER_PROFILE_EDIT_ROOT

}